/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\potato\\Desktop\\vp-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-65702a51",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65702a51").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-89678d2a",
    path: "/blogs/back-end/Git%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-89678d2a").then(next)
    },
  },
  {
    path: "/blogs/back-end/Git学习.html",
    redirect: "/blogs/back-end/Git%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/back-end/Git学习.html",
    redirect: "/blogs/back-end/Git%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-18358627",
    path: "/blogs/back-end/Linux%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-18358627").then(next)
    },
  },
  {
    path: "/blogs/back-end/Linux学习.html",
    redirect: "/blogs/back-end/Linux%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/back-end/Linux学习.html",
    redirect: "/blogs/back-end/Linux%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-449a070c",
    path: "/blogs/back-end/Linux%E5%AE%9E%E6%93%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-449a070c").then(next)
    },
  },
  {
    path: "/blogs/back-end/Linux实操.html",
    redirect: "/blogs/back-end/Linux%E5%AE%9E%E6%93%8D.html"
  },
  {
    path: "/blogs/back-end/Linux实操.html",
    redirect: "/blogs/back-end/Linux%E5%AE%9E%E6%93%8D.html"
  },
  {
    name: "v-72c529bf",
    path: "/blogs/back-end/SpringBoot%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72c529bf").then(next)
    },
  },
  {
    path: "/blogs/back-end/SpringBoot学习.html",
    redirect: "/blogs/back-end/SpringBoot%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/back-end/SpringBoot学习.html",
    redirect: "/blogs/back-end/SpringBoot%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-176d0e2e",
    path: "/blogs/back-end/MyBatis%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-176d0e2e").then(next)
    },
  },
  {
    path: "/blogs/back-end/MyBatis学习.html",
    redirect: "/blogs/back-end/MyBatis%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/back-end/MyBatis学习.html",
    redirect: "/blogs/back-end/MyBatis%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-63233f75",
    path: "/blogs/back-end/SpringMVC%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63233f75").then(next)
    },
  },
  {
    path: "/blogs/back-end/SpringMVC学习.html",
    redirect: "/blogs/back-end/SpringMVC%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/back-end/SpringMVC学习.html",
    redirect: "/blogs/back-end/SpringMVC%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-27861602",
    path: "/blogs/back-end/Spring%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-27861602").then(next)
    },
  },
  {
    path: "/blogs/back-end/Spring学习.html",
    redirect: "/blogs/back-end/Spring%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/back-end/Spring学习.html",
    redirect: "/blogs/back-end/Spring%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-49aff255",
    path: "/blogs/front-end/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49aff255").then(next)
    },
  },
  {
    path: "/blogs/front-end/前端基础.html",
    redirect: "/blogs/front-end/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80.html"
  },
  {
    path: "/blogs/front-end/前端基础.html",
    redirect: "/blogs/front-end/%E5%89%8D%E7%AB%AF%E5%9F%BA%E7%A1%80.html"
  },
  {
    name: "v-25c0ff7f",
    path: "/blogs/python/Python%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-25c0ff7f").then(next)
    },
  },
  {
    path: "/blogs/python/Python学习.html",
    redirect: "/blogs/python/Python%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/blogs/python/Python学习.html",
    redirect: "/blogs/python/Python%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-cec608ca",
    path: "/blogs/java/Java%E7%BC%96%E7%A8%8B%E6%80%9D%E6%83%B3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cec608ca").then(next)
    },
  },
  {
    path: "/blogs/java/Java编程思想.html",
    redirect: "/blogs/java/Java%E7%BC%96%E7%A8%8B%E6%80%9D%E6%83%B3.html"
  },
  {
    path: "/blogs/java/Java编程思想.html",
    redirect: "/blogs/java/Java%E7%BC%96%E7%A8%8B%E6%80%9D%E6%83%B3.html"
  },
  {
    name: "v-3527532e",
    path: "/blogs/python/Python%E7%88%AC%E8%99%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3527532e").then(next)
    },
  },
  {
    path: "/blogs/python/Python爬虫.html",
    redirect: "/blogs/python/Python%E7%88%AC%E8%99%AB.html"
  },
  {
    path: "/blogs/python/Python爬虫.html",
    redirect: "/blogs/python/Python%E7%88%AC%E8%99%AB.html"
  },
  {
    name: "v-429dbb56",
    path: "/blogs/java/Java%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-429dbb56").then(next)
    },
  },
  {
    path: "/blogs/java/Java并发编程.html",
    redirect: "/blogs/java/Java%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B.html"
  },
  {
    path: "/blogs/java/Java并发编程.html",
    redirect: "/blogs/java/Java%E5%B9%B6%E5%8F%91%E7%BC%96%E7%A8%8B.html"
  },
  {
    name: "v-7053b774",
    path: "/blogs/java/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3Java%E8%99%9A%E6%8B%9F%E6%9C%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7053b774").then(next)
    },
  },
  {
    path: "/blogs/java/深入理解Java虚拟机.html",
    redirect: "/blogs/java/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3Java%E8%99%9A%E6%8B%9F%E6%9C%BA.html"
  },
  {
    path: "/blogs/java/深入理解Java虚拟机.html",
    redirect: "/blogs/java/%E6%B7%B1%E5%85%A5%E7%90%86%E8%A7%A3Java%E8%99%9A%E6%8B%9F%E6%9C%BA.html"
  },
  {
    name: "v-251bac39",
    path: "/blogs/python/%E6%B5%81%E7%95%85%E7%9A%84Python.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-251bac39").then(next)
    },
  },
  {
    path: "/blogs/python/流畅的Python.html",
    redirect: "/blogs/python/%E6%B5%81%E7%95%85%E7%9A%84Python.html"
  },
  {
    path: "/blogs/python/流畅的Python.html",
    redirect: "/blogs/python/%E6%B5%81%E7%95%85%E7%9A%84Python.html"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-28e6393c",
    path: "/category/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-28e6393c").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/category/index.html",
    redirect: "/category/"
  },
  {
    name: "v-9e6f27fc",
    path: "/archive/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-9e6f27fc").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/archive/index.html",
    redirect: "/archive/"
  },
  {
    name: "v-32555732",
    path: "/tag/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-32555732").then(next)
    },
    meta: {"pid":"tags","id":"Git"}
  },
  {
    path: "/tag/Git/index.html",
    redirect: "/tag/Git/"
  },
  {
    name: "v-e14f25f6",
    path: "/tag/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e14f25f6").then(next)
    },
    meta: {"pid":"tags","id":"Linux"}
  },
  {
    path: "/tag/Linux/index.html",
    redirect: "/tag/Linux/"
  },
  {
    name: "v-29013a71",
    path: "/tag/Spring Boot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-29013a71").then(next)
    },
    meta: {"pid":"tags","id":"Spring Boot"}
  },
  {
    path: "/tag/Spring Boot/index.html",
    redirect: "/tag/Spring Boot/"
  },
  {
    name: "v-f5f3b4b4",
    path: "/tag/MyBatis/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-f5f3b4b4").then(next)
    },
    meta: {"pid":"tags","id":"MyBatis"}
  },
  {
    path: "/tag/MyBatis/index.html",
    redirect: "/tag/MyBatis/"
  },
  {
    name: "v-6cb21221",
    path: "/tag/Spring MVC/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6cb21221").then(next)
    },
    meta: {"pid":"tags","id":"Spring MVC"}
  },
  {
    path: "/tag/Spring MVC/index.html",
    redirect: "/tag/Spring MVC/"
  },
  {
    name: "v-4bb4ec90",
    path: "/tag/Spring/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4bb4ec90").then(next)
    },
    meta: {"pid":"tags","id":"Spring"}
  },
  {
    path: "/tag/Spring/index.html",
    redirect: "/tag/Spring/"
  },
  {
    name: "v-e1d2b37c",
    path: "/tag/Front-End/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-e1d2b37c").then(next)
    },
    meta: {"pid":"tags","id":"Front-End"}
  },
  {
    path: "/tag/Front-End/index.html",
    redirect: "/tag/Front-End/"
  },
  {
    name: "v-4aea34c9",
    path: "/tag/Python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4aea34c9").then(next)
    },
    meta: {"pid":"tags","id":"Python"}
  },
  {
    path: "/tag/Python/index.html",
    redirect: "/tag/Python/"
  },
  {
    name: "v-18082c7a",
    path: "/tag/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-18082c7a").then(next)
    },
    meta: {"pid":"tags","id":"Java"}
  },
  {
    path: "/tag/Java/index.html",
    redirect: "/tag/Java/"
  },
  {
    name: "v-13311205",
    path: "/tag/爬虫/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-13311205").then(next)
    },
    meta: {"pid":"tags","id":"爬虫"}
  },
  {
    path: "/tag/爬虫/index.html",
    redirect: "/tag/爬虫/"
  },
  {
    name: "v-28437576",
    path: "/tag/Java并发/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-28437576").then(next)
    },
    meta: {"pid":"tags","id":"Java并发"}
  },
  {
    path: "/tag/Java并发/index.html",
    redirect: "/tag/Java并发/"
  },
  {
    name: "v-6255d1a7",
    path: "/tag/虚拟机/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-6255d1a7").then(next)
    },
    meta: {"pid":"tags","id":"虚拟机"}
  },
  {
    path: "/tag/虚拟机/index.html",
    redirect: "/tag/虚拟机/"
  },
  {
    name: "v-4d1cb3c4",
    path: "/category/Back-End/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-4d1cb3c4").then(next)
    },
    meta: {"pid":"categories","id":"Back-End"}
  },
  {
    path: "/category/Back-End/index.html",
    redirect: "/category/Back-End/"
  },
  {
    name: "v-190f1358",
    path: "/category/Front-End/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-190f1358").then(next)
    },
    meta: {"pid":"categories","id":"Front-End"}
  },
  {
    path: "/category/Front-End/index.html",
    redirect: "/category/Front-End/"
  },
  {
    name: "v-011eadf7",
    path: "/category/Python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-011eadf7").then(next)
    },
    meta: {"pid":"categories","id":"Python"}
  },
  {
    path: "/category/Python/index.html",
    redirect: "/category/Python/"
  },
  {
    name: "v-25b8d671",
    path: "/category/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-25b8d671").then(next)
    },
    meta: {"pid":"categories","id":"Java"}
  },
  {
    path: "/category/Java/index.html",
    redirect: "/category/Java/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]