/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Git": {
      "key": "Git",
      "scope": "tags",
      "path": "/tag/Git/",
      "pageKeys": [
        "v-89678d2a"
      ]
    },
    "Linux": {
      "key": "Linux",
      "scope": "tags",
      "path": "/tag/Linux/",
      "pageKeys": [
        "v-18358627",
        "v-449a070c"
      ]
    },
    "Spring Boot": {
      "key": "Spring Boot",
      "scope": "tags",
      "path": "/tag/Spring Boot/",
      "pageKeys": [
        "v-72c529bf"
      ]
    },
    "MyBatis": {
      "key": "MyBatis",
      "scope": "tags",
      "path": "/tag/MyBatis/",
      "pageKeys": [
        "v-176d0e2e"
      ]
    },
    "Spring MVC": {
      "key": "Spring MVC",
      "scope": "tags",
      "path": "/tag/Spring MVC/",
      "pageKeys": [
        "v-63233f75"
      ]
    },
    "Spring": {
      "key": "Spring",
      "scope": "tags",
      "path": "/tag/Spring/",
      "pageKeys": [
        "v-27861602"
      ]
    },
    "Front-End": {
      "key": "Front-End",
      "scope": "tags",
      "path": "/tag/Front-End/",
      "pageKeys": [
        "v-49aff255"
      ]
    },
    "Python": {
      "key": "Python",
      "scope": "tags",
      "path": "/tag/Python/",
      "pageKeys": [
        "v-25c0ff7f",
        "v-251bac39"
      ]
    },
    "Java": {
      "key": "Java",
      "scope": "tags",
      "path": "/tag/Java/",
      "pageKeys": [
        "v-cec608ca"
      ]
    },
    "爬虫": {
      "key": "爬虫",
      "scope": "tags",
      "path": "/tag/爬虫/",
      "pageKeys": [
        "v-3527532e"
      ]
    },
    "Java并发": {
      "key": "Java并发",
      "scope": "tags",
      "path": "/tag/Java并发/",
      "pageKeys": [
        "v-429dbb56"
      ]
    },
    "虚拟机": {
      "key": "虚拟机",
      "scope": "tags",
      "path": "/tag/虚拟机/",
      "pageKeys": [
        "v-7053b774"
      ]
    }
  },
  "categories": {
    "Back-End": {
      "key": "Back-End",
      "scope": "categories",
      "path": "/category/Back-End/",
      "pageKeys": [
        "v-89678d2a",
        "v-18358627",
        "v-449a070c",
        "v-72c529bf",
        "v-176d0e2e",
        "v-63233f75",
        "v-27861602"
      ]
    },
    "Front-End": {
      "key": "Front-End",
      "scope": "categories",
      "path": "/category/Front-End/",
      "pageKeys": [
        "v-49aff255"
      ]
    },
    "Python": {
      "key": "Python",
      "scope": "categories",
      "path": "/category/Python/",
      "pageKeys": [
        "v-25c0ff7f",
        "v-3527532e",
        "v-251bac39"
      ]
    },
    "Java": {
      "key": "Java",
      "scope": "categories",
      "path": "/category/Java/",
      "pageKeys": [
        "v-cec608ca",
        "v-429dbb56",
        "v-7053b774"
      ]
    }
  },
  "timeline": {}
}